services:
  sass-launchpad-db:
    image: postgres:16
    environment:
      POSTGRES_DB: sass-launchpad
      POSTGRES_USER: sass-launchpad-user
      POSTGRES_PASSWORD: sass-launchpad-password
    volumes:
      - postgres_data:/var/lib/postgresql/sass-launchpad-data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sass-launchpad-user -d sass-launchpad"]
      interval: 10s
      timeout: 5s
      retries: 5

  sass-launchpad-api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://sass-launchpad-user:sass-launchpad-password@sass-launchpad-db:5432/sass-launchpad
    ports:
      - "8000:8000"
    depends_on:
      sass-launchpad-db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
      - ./:/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
